### ISSUE TITLE
need a little help understanding and solving signal errors

### ISSUE THREAD

**Issue by Connoropolous** [holochain/tx5#34]
we have the goal to compile and run holochain natively on ios, and it's almost working. Zome calls are working, but gossip isn't. here's what we're now seeing in the logs. We are now using `wss://signal.holotest.net`, which corrected the initial error that we were previously having.

```
try connect addr=167.71.76.147:443
err=Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: UnknownIssuer") }
failed all sig dns addr connects
```

is the cause of this obvious to you @neonphog ?

**Comment by neonphog** [comment]
@Connoropolous - can you go to https://signal.holotest.net/metrics on the device you're testing on and see what it says about the cert?

In the mean time, I'll look into the go lib to see if it's using some alternate TLS validation other than the native system one.

**Comment by neonphog** [comment]
There's very little information, possibly because it looks like it's just built-in that it uses the native device certs:

[https://pkg.go.dev/crypto/tls#Config](https://pkg.go.dev/crypto/tls#Config)

```go
// RootCAs defines the set of root certificate authorities
// that clients use when verifying server certificates.
// If RootCAs is nil, TLS uses the host's root CA set.
RootCAs *[x509](https://pkg.go.dev/crypto/x509).[CertPool](https://pkg.go.dev/crypto/x509#CertPool)
```

Is it possible the device you are testing on hasn't had an update in long enough that Let's Encrypt root CA is not up-to-date on it?

**Comment by neonphog** [comment]
Also looks like you need iOS >= 9 (~2015) - https://www.ssllabs.com/ssltest/analyze.html?d=signal.holotest.net

**Comment by Connoropolous** [comment]
I visited, and it says 'connection is secure' from an iPhone XR, with iOS 16.4.1

**Comment by Connoropolous** [comment]
can you give a bit more background.
what server is this? 167.71.76.147:443 (from `try connect addr=167.71.76.147:443`)

**Comment by Connoropolous** [comment]
that is the signal server ip I guess, based on using `ping signal.holotest.net`

**Comment by neonphog** [comment]
@Connoropolous - Double check my logic - it looks like [rustls-native-certs](https://github.com/rustls/rustls-native-certs/issues/3) doesn't support ios, and the recommendation is to instead use [https://github.com/rustls/rustls-platform-verifier](https://github.com/rustls/rustls-platform-verifier)... but that crate seems to have been deleted from crates.io.

I will look into it further tomorrow.

**Comment by neonphog** [comment]
If nothing else, I guess we could use [webpki-roots](https://crates.io/crates/webpki-roots) on android and ios.

**Comment by Connoropolous** [comment]
Your logic seems right. It seems to me that this particular comment has a simple solution that could work. https://github.com/rustls/rustls-native-certs/issues/3#issuecomment-1494166114

**Comment by Connoropolous** [comment]
The same solution that is being used for macOS should work with iOS, so just including it through the targets
https://github.com/rustls/rustls-native-certs/blob/88066f5eebeabf034a5a1deda83c6214b3d024c9/src/lib.rs#L36

**Comment by neonphog** [comment]
@Connoropolous - as I don't have a good way to directly test such a fix, I wouldn't be comfortable submitting a PR to their repo.

I'll work on the webpki-roots fallback in our code, since it looks like we'll need that for android anyways. If you'd like to submit a PR for rustls-native-certs, then I can remove ios from the fallback set if/when it gets merged.

**Comment by Connoropolous** [comment]
Ok thankyou. We will await your solution and try it before doing anything else

**Comment by Connoropolous** [comment]
Will you give me a heads up here?

**Comment by neonphog** [comment]
@Connoropolous - can you give this a try? https://github.com/holochain/tx5/pull/35 Thanks!

**Comment by Connoropolous** [comment]
Yes absolutely, asap

**Comment by Connoropolous** [comment]
Thanks!

**Comment by Connoropolous** [comment]
Updating the stack to use this branch you posted worked to resolve the error!
Now attempting hands on testing

**Comment by neonphog** [comment]
PR to potentially backport to 0.2: https://github.com/holochain/holochain/pull/2415

**Comment by Connoropolous** [comment]
k. as I've done hands on testing, I've had inconclusive results. @neonphog I am wondering if its mandatory that tx2 still be enabled. Why is it?
Here's my writeup on how things are going, and where we're stuck.
https://hackmd.io/_CFnGaWvQg6Ys3DxZblmug

**Comment by neonphog** [comment]
@Connoropolous - To get some additional hints into the tx5 state machine: `RUST_LOG=info,tx5::state=debug`

**Comment by Connoropolous** [comment]
thanks

**Comment by Connoropolous** [comment]
@neonphog I've just tried updating to 0.3.0-beta-dev.0

Here's my update, can you take a peek, does the error make any sense to you?
https://hackmd.io/_CFnGaWvQg6Ys3DxZblmug?view#May-23

**Comment by neonphog** [comment]
@Connoropolous - I just created this issue: https://github.com/holochain/holochain/issues/2422

**Comment by Connoropolous** [comment]
Fantastic thanks
