### ISSUE TITLE
Document issue `Undefined symbols for architecture arm64: "_res_9_nclose"`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/tx5#74]
When building for iOS, linking from go 1.20 or more gives this error:

```
Undefined symbols for architecture arm64:
"_res_9_nclose", referenced from:
_internal/syscall/unix.libresolv_res_9_nclose_trampoline.abi0 in Libtest(go.o)
"_res_9_ninit", referenced from:
_internal/syscall/unix.libresolv_res_9_ninit_trampoline.abi0 in Libtest(go.o)
"_res_9_nsearch", referenced from:
_internal/syscall/unix.libresolv_res_9_nsearch_trampoline.abi0 in Libtest(go.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The solution is documented [here](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html):

1. Run the project with Xcode
2. Link libresolv.tbd and libresolv.9.tbd. Click the + at the bottom of the Linked Frameworks list and type libresolv into the search box. Select libresolv.tbd and then “Add”.

**Comment by neonphog** [comment]
Hmm... we are [already trying to link against libresolv](https://github.com/holochain/tx5/blob/c7c61df55676e5dc17075c85b6d658113e8867d9/crates/tx5-go-pion-sys/src/lib.rs#L25-L28) which works for macOS. I wonder if it has to be constructed differently to work on iOS?
