### ISSUE TITLE
API consistency for `peer_url` vs `id`

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/tx5#90]
Endpoint events are implemented in terms of peer_url -> https://github.com/holochain/tx5/blob/main/crates/tx5/src/ep3.rs#L41

But endpoint functions like `ban` take an `id` -> https://github.com/holochain/tx5/blob/main/crates/tx5/src/ep3.rs#L406

You can get from one to the other by doing `peer_url.id().unwrap()` if you know that your `peer_url` is a peer URL and not a server URL. It would be nicer to absorb this check and conversion into the endpoint API and let consumers just work in terms of `peer_url`.

**Comment by neonphog** [comment]
pub_key (formerly id) is now no longer an Option: https://github.com/holochain/tx5/blob/e8c1a1b68a18087ce392db0c684118919ed13224/crates/tx5/src/url.rs#L213-L216
